services:
  backendtracker:
    image: backendtracker
    build:
      context: .
      dockerfile: BackendTracker/Dockerfile
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: tracker
    ports:
      - "5432:5432"

